language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ehKxbiTbzS6+2McgdkOPXq573ZDuYDqQ91BzYRFpbJhsyuJBbVW/y7gF6pGkJCAxF4peF1FtiLEg5TTZNHUS+RxlSkHuA6YZHyDRhnlEyNg8F2XJ4SeFIO2t1DAMzZAFu+5t18qK48Gyx1gql4dAWXoYVm5l2+6glc/x4DLdjWgEM4Wppbud35e92ZKcgHeclcaB3IzZ+KYlVT1xWm5uYeGcie0fkvGb4E4CcO52SbCUiRD6FUwkDbxzmqwpETV0UJwN9p34gPVyeZ5RFjZ4hUem4ukeS5riKn2jtsNYyV3NrE8yV0SXJMae9ZatXg++BhbgGmV07vMpWKpuFSeJ+A0gdU1vy895braT0oS3OFlEjsucCbl71fNdYUpkFjbqFefgCiE0kRG7r1z9paEXZ6FUJjp3b9pFnptwaUDMFomtMMrbWPirQs6TRMOUw7U2UHpbL7c0dwSsCtuh1B0rV04ep7MIDjkRunhbrPebFuQqmqMVM9CqLN5m77Gl+1JbO9iFCdK59G8FirbQTRVh5YyvhnyrxhPK8J4gOQJ8Qpoqb345dML6WTqg7KVH402oOiJcboY4m9he9xR3Vk1KDBx9d9KTedXH+9+1D8+4M4dW6tIozoznGP4XDQz4QdzQ8948N/OS9iwSLTWMrMZ4uzKjTZR3F2QWtI32HbLk1YQ=
  app: bestow-api
  on:
    repo: Mrjustinfry/bestow-api
